language: perl
perl:
#  - "5.16"
#  - "5.14"

before_install:
    - sudo apt-get install libmodern-perl-perl
    - sudo xargs aptitude --schedule-only install < ./deb-deps 
    - sudo aptitude install
#    - cpanm Test::Pod # optional dependency

#install: bash -x ./install-deps.sh
install: bash -x ./install-deps2.sh

script: perl ./t/Perl.t
