language: perl
perl:
#  - "5.10"
#  - "5.12"
#  - "5.14"
#  - "5.16"
#  - "5.18"

before_install:
    - sudo apt-get install aptitude
    - sudo xargs aptitude --schedule-only install < ./deb-deps
    - sudo aptitude -y install
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
#    - cpanm Test::Pod # optional dependency

install:
     - export PERL5LIB="${PERL5LIB}":/usr/share/perl5
     - export | grep PERL5LIB
     - bash -x ./install-cpan-deps.sh
     - cpanm -S -v Modern::Perl
     - cpanm -S -v Test::Perl::Critic::Progressive
     - cpanm -S -v Git::Repository

#install: bash -x ./install-deps2.sh
#install: bash -x ./install-deps2.sh

script: perl ./t/Perl.t
